### ISSUE TITLE
Jupyter Lab

### ISSUE THREAD

**Issue by ChasNelson1990** [ChasNelson1990/python-zero-to-hero-course#12]
Now that Jupyter Lab 1.0+ has been released I intend to move the course onto it.

I think Lab is a much better interface for newbies.

I note that Conda still seems to be using 0.35 so will wait till then to do the update.

**Comment by ChasNelson1990** [comment]
Conda did update and Jupyter Lab is preinstalled (according to docs). Made changes. @mixmixmix I'd appreciate if you could check there's nothing odd about Mac? I checked linux and the Windows docs.

**Comment by mixmixmix** [comment]
I will check it.

**Comment by mixmixmix** [comment]
Works fine on mac! I'm not 100% sure it will be easier for everyone, but definitely for most, and will pay back almost immediately when they start working on their own.
