### ISSUE TITLE
Future Plans

### ISSUE THREAD

**Issue by ChasNelson1990** [ChasNelson1990/python-zero-to-hero-course#13]
I've created three new labels and two new milestones on the GitHub and I'd like you help creating a tonne of issues for them (and then, over time, helping me close said issues).

The labels are:
* demo - for new demonstrations/examples we think we should add
* exercise - for new exercises we think we should add
* video - for places we think there should be videos (I would expect any issue for the above label will also likely need this label)

The milestones are:
* RSB  course #2
* On-line course

I'm going through and noting some things now but would appreciate it if you could perhaps do the same independently? Perhaps even make a list without looking at the issues I've created and see where we match (you could add a comment to those, I guess).

If you do start to make some changes as well then, at the moment, there will be up to four copies of each notebook (BTW very happy for ideas on how to streamline this; I think maybe we should have two repositories?):
1. In the folder `notebooks`, these are the notebooks (one per 'chapter') with uncompleted cells and empty spaces for exercises and demos to be used on the physical course. These should always be saved in a cleared state. [Exists]
2. In the `slides` folder, this is a super-notebook with reveal.js metadata. This should be kept in sync with chapters 1--9 and 13 but will be different for chapters 9--12. This should not include the objectives or key points from any chapter. These should always be saved in a cleared state. [Exists]
3. If we decide to stick with one repository then we will need a folder with the notebooks to be hosted on binder. This could be identical to `notebooks` (negating the need for a new folder) but I think it will have more examples and exercises? This should always be saved in a cleared state. [Does not exist]
4. Finally, there should be a completed-answer notebook for each chapter. This should be in sync with the 'superset' of each chapter, probably item number 3. This should always be saved in a completed state (some small modifications/manual cell running may have to be included to ensure that desired error messages appear but that the rest of the notebook still runs.) [Does not exist]

I'll wait for your comments on everything above before I add any issues/create new folders or copies. Particularly with reference to 1 repo or 2.

**Comment by ChasNelson1990** [comment]
@mixmixmix nudge on this one ;-)

**Comment by ChasNelson1990** [comment]
@mixmixmix nudge on this one ;-)

**Comment by mixmixmix** [comment]
Thanks for nudging! :o) 

Do you want me to create "tonnes" of issues, or just clear up #11  ? Because I see you were keeping some tasks in there. 

Re 1: I would treat those in `notebooks` as the _main copies_. 
Re 2: I would do the slides only after we are satisfied with changes to the main body of the course. There still might be some changes to the _main copies_ required by slide format, but I estimate it would be less work to do those in one go. 
Re 3: I think we should make "Additional exercises" add the end of each notebook. Then to time them separately and exclusively of the rest of the course. (I would actually time the whole notebook with in-course exercises by giving it to some non-pythonic friends to go through and just allow them to ask questions.)
Re 4: Yet again, I suggest we add completed books at the very end after all else is done. I agree it is essential.

**Comment by mixmixmix** [comment]
About milestones. RBS course has a deadline later than on-line one, but I can't think of many issues that are specific to it and won't affect the online course content which we need to sort out earlier. Therefore almost all issues can be milestoned for Online course.

**Comment by ChasNelson1990** [comment]
I like milestones....
--
Sent from my Android device with K-9 Mail. Please excuse my brevity.

On 14 August 2019 18:27:12 BST, "M. Kunde" <notifications@github.com> wrote:

About milestones. RBS course has a deadline later than on-line one, but I can't think of many issues that are specific to it and won't affect the online course content which we need to sort out earlier. Therefore almost all issues can be milestoned for Online course.

**Comment by mixmixmix** [comment]
As you've noticed the exercises I add are sometimes more challenging, they usually require looking up documentation even before we talk about it. But I think it is fine because they would be done after completing the whole day of the course.

**Comment by ChasNelson1990** [comment]
Discussed in person.
