### ISSUE TITLE
I don't get the pun with our new name

### ISSUE THREAD

**Issue by mixmixmix** [ChasNelson1990/python-zero-to-hero-course#14]
"Python: Hero-to-Zero 1 day course"
explain? ;)f

**Comment by ChasNelson1990** [comment]
It's not a pun. It's a common way of saying it's a basics course.

But if you don't like it feel free to change.

**Comment by mixmixmix** [comment]
It is the wrong way round then :D

**Comment by ChasNelson1990** [comment]
Oh... yea.... it is... wow... did not see that.
