### ISSUE TITLE
Presentation of notebook slides

### ISSUE THREAD

**Issue by mixmixmix** [ChasNelson1990/python-zero-to-hero-course#17]
I think some of the text from the notebooks should be skipped for slides, or shortened. For instance disclaimer about `.format()`.
Not sure how to do it best, possibly once we finish polishing notebooks, to take a look and make shortened versions of some longer texts.
What do you think @chasnelson?

**Comment by ChasNelson1990** [comment]
I agree. Let's polish notebooks first and then sit-down (with a coffee) to polish slides :-).

**Comment by ChasNelson1990** [comment]
This is totally on me. I'll do it next week.
