### ISSUE TITLE
Exercises at the end of a notebook

### ISSUE THREAD

**Issue by mixmixmix** [ChasNelson1990/python-zero-to-hero-course#20]
Having exercises in the main body of a notebook can distract (both positively and negatively ;P) the participants. It is also easier to create reinforcement exercises having the material from the whole notebook to play with. Also for video version I think it would be easier to have all exercises in one place (per notebook)
What are your thoughts?

**Comment by ChasNelson1990** [comment]
Some 'Challenges' now added. Would be good to add more.

**Comment by ChasNelson1990** [comment]
Going to close this but we should think about this again in the wrap up of the RSB course.

**Comment by mixmixmix** [comment]
![Image of Python](https://imgs.xkcd.com/comics/python.png )
