### ISSUE TITLE
Unlike with local notebooks, binder won't save progress and notes of students

### ISSUE THREAD

**Issue by mixmixmix** [ChasNelson1990/python-zero-to-hero-course#21]
- [ ] investigate saving notebooks from binder
- [ ] Add an introduction page for the course explaining this issue and suggesting that the course can be run locally as well
- [ ] Suggest taking notes?

**Comment by ChasNelson1990** [comment]
Or... don't use binder and just get them to download the notebooks from my website and install anaconda locally? We could add an installation video.
What do you think?

**Comment by mixmixmix** [comment]
Issues #22  is of course making it a little bit worse (kicking out after inactivity). I think we should make sure that we provide link to setup document so that more tech savvy participants can install anaconda.

**Comment by ChasNelson1990** [comment]
Hmmm... I think I've convinced myself we should do Anaconda only... that way they all have Python and stuff locally and don't try to find away to create new projects on Binder...
