### ISSUE TITLE
comments on notebook 13

### ISSUE THREAD

**Issue by mixmixmix** [ChasNelson1990/python-zero-to-hero-course#25]
Anonymous wrote:
> What would be helpful for me at the beginning with matplotlib, is showing the preliminary structure of codes for plotting. While method based on trying, failing and researching is great, it may be time consuming for a one day course. But when later you introduce seaborn, everything’s fine, so I don’t know anymore.

**Comment by ChasNelson1990** [comment]
That's a really good point. I think I have an idea and think we should include it for this month's RSB course.
