### ISSUE TITLE
What to do about slides?

### ISSUE THREAD

**Issue by ChasNelson1990** [ChasNelson1990/python-zero-to-hero-course#37]
We originally decided that slides should be standalone so that we could modify them a bit... however, this means they get out of sync with the notebooks. This is less than ideal.

There are three ways forward:
1) we keep stuff as it is
2) we work out some way to keep the slides and notebooks in sync where they should be but different where we want them different
3) we suck it up and just present the notebooks; we can use the cell properties to control which cells are on the same slide or which are skipped just like we do with slides.ipynb but we can generate and present the slides on the fly on the day

Thoughts?

**Comment by mixmixmix** [comment]
I prefer option 3. I think that adding a "slide" cell which has keywords and main pointers, followed by "skip" cell that has all the stuff we want people to read if they cannot hear us. With examples and code it is always a little bit messy anyway.

**Comment by ChasNelson1990** [comment]
Excellent, will action!
