### ISSUE TITLE
Generating reports from jupyter

### ISSUE THREAD

**Issue by mixmixmix** [ChasNelson1990/python-zero-to-hero-course#5]
I've heard you can turn jupyter notebooks into some sort of printed media. If it is true, then I think that would be super helpful to show. 

What do you think? Do you know about it @ChasNelson1990 ?

**Comment by ChasNelson1990** [comment]
Yea... it's not always perfect with long lines. But good idea.
https://nbconvert.readthedocs.io/en/latest/

I think I'll add it at the very end. I.e. get them to export everything they've done during the day. What do you think?

**Comment by ChasNelson1990** [comment]
We didn't do this. I think it's quite easy to learn on-line so will close this issue.
