### ISSUE TITLE
Additional exercises?

### ISSUE THREAD

**Issue by mixmixmix** [ChasNelson1990/python-zero-to-hero-course#6]
Are we adding some additional exercises? I think at the end of, let's say notebook 8, attendees should have enough knowledge to do something more interesting. We might have a few who will be going ahead, so additional exercises can keep them busy. What do you think @ChasNelson1990 ?

**Comment by ChasNelson1990** [comment]
So my planned schedule is below. I'm asking them to bring their own data, just one file, and the plan is that from "Data Frames with pandas", they'll be working on their own data and the notebooks will be almost empty apart from some introductory text and a very broad task.

- REGISTRATION (inc. Installation Help)
- Introduction
- Running Python in Jupyter Notebooks
- Basic Python Syntax and Variables
- Data Types in Python
- Built-in Functions, Help and Documentation
- COFFEE (inc. group discussions)
- The Python list Data Type
- Loops in Python (for and while)
- Python Conditionals (if Statements)
- Writing Your Own Functions
- Variable Scope (Local vs Global)
- LUNCH (inc. group discussions)
- Q&A
- Python Packages
- NumPy and SciPy
- Data Frames with pandas
- Reading Your Own Data
- COFFEE (inc. group discussions)
- Looping Over Data
- Plotting with Seaborn
- Plotting with matplotlib
- Programming Style
- Where to go now?
- END

I will add a schedule to the repository, once I've worked out all the times.

**Comment by ChasNelson1990** [comment]
Also, I was thinking of adding a couple of extra exercises at the bottom of each notebook - with the idea that they do those at home (or if they whizz through they can do them on the day I suppose).

**Comment by ChasNelson1990** [comment]
Additional: the notebooks I wrote on 2019-03-24 are a bit light on exercises. I think I need to add one 'do it yourself from scratch' exercise at the end of each.

**Comment by ChasNelson1990** [comment]
Moving this into the new post-course issue.
