### ISSUE TITLE
Additional links and materials

### ISSUE THREAD

**Issue by mixmixmix** [ChasNelson1990/python-zero-to-hero-course#7]
Since we don't have a file for that, I'll post my ideas here:

Using unix, best tutorial ever:
http://www.ee.surrey.ac.uk/Teaching/Unix/index.html

**Comment by ChasNelson1990** [comment]
So, it was not my plan to try and win them over to a unix system.

*But*, I have been thinking that we should have a one page PDF on resources they might like to investigate after the course.

I have created a markdown file and added this link. Feel free to add more but we may choose to prune later on.
