### ISSUE TITLE
Do we introduce the Notebook GUI as well as keyboard options?

### ISSUE THREAD

**Issue by ChasNelson1990** [ChasNelson1990/python-zero-to-hero-course#8]
@mixmixmix wrote:

> TODO for Chas: I think we don't need a task here, and if then something quicker. Describing GUI interface actions is horrible :P

But, many of these users are very used to using the mouse. Do you not think it's worth giving them the option of mouse or keyboard?

I've removed this comment from the notebook (and left the task in) but happy for you to remove it (and close this) if you really think it doesn't help.

**Comment by mixmixmix** [comment]
I like the task! Just writing down the instructions for them would be difficult. 
> To write this comment I had to click in a textbox below the most recent comment, and then click green button "Comment" on the bottom right corner below the box. and so on. But I might be exaggerating. :D

**Comment by mixmixmix** [comment]
I like the task! Just writing down the instructions for them would be difficult. 
> To write this comment I had to click in a textbox below the most recent comment, and then click green button "Comment" on the bottom right corner below the box. and so on. But I might be exaggerating. :D

**Comment by ChasNelson1990** [comment]
I don't understand you. Please clarify.

**Comment by mixmixmix** [comment]
nevermind, it'll be ok
