### ISSUE TITLE
Using a variable for different data types.

### ISSUE THREAD

**Issue by ChasNelson1990** [ChasNelson1990/python-zero-to-hero-course#9]
@mixmixmix wrote:
> #TODO Chas, Maybe we should also here tell them that they should never reuse the same variable for different types?

I mean... I don't think I ever do this but I also don't think I've ever been told it's bad practice.

What's your thinking here?

**Comment by ChasNelson1990** [comment]
Also, I've highlighted this #TODO in bright red (#FF0000) and 'strong'.

Perhaps we could do this for all in-line TODOs - so they can be spotted easily.

**Comment by mixmixmix** [comment]
I prefer just `Ctrl+F` it, don't you ;)

**Comment by mixmixmix** [comment]
or `grep -r TODO .`
